type: AgentShowcase
params:
  inject_till: 7700
effectors:
  - type: BallInjector
    params:
      locally_random: True
      radius: 0.05
      flux: 10
      init_pos: (0.8, 0.8, 0.5)
      inject_v: (-1.3, 0.0, 0.0)
      action_dim: 3
      action_scale_p: (1.0, 1.0, 1.0)
      action_scale_v: (1.0, 1.0, 1.0)
    boundary:
      type: cube
      lower: (0.05, 0.05, 0.05)
      upper: (0.95, 0.95, 0.95)